rendering: False
nb_experiments: 1
random_seed: 1234
total_eps: 10000
total_test_eps: 1
is_learning: True
eps_per_epoch: 10
max_start_nullops: 0
is_testing: True
eps_per_test: 1
episode_max_len: 10000
step_max_len: 1000
folder_location: '/results/'
test: False
transfer: False

annealing: True
annealing_episodes: 10000
epsilon: 1.0
final_epsilon: 0.001
test_epsilon: 0.001

is_aggregator: True

annealing_lr: False
learning_rate: 0.001 # default
transfer_lr: 0.0001
final_lr: 0.00001

minibatch_size: 32
history_len: 1
replay_max_size: 50000
replay_min_size: 5000
learning_frequency: 100
update_freq: 20
action_dim: 1
num_units: 250

draw_graph_freq: 20
draw_cv2_freq: 1000
draw_movie_freq: 1000

test_draw_cv2_freq: 1
test_draw_movie_freq: 1

