rendering: False
nb_experiments: 1
random_seed: 1234
total_eps: 3000
is_learning: True
eps_per_epoch: 10
max_start_nullops: 0
is_testing: True
eps_per_test: 1
episode_max_len: 3000
step_max_len: 1500
folder_location: '/results/'
test: False

annealing: True
annealing_episodes: 3000
epsilon: 1.0
final_epsilon: 0.05
test_epsilon: 0.001

learning_rate: 0.001
minibatch_size: 32
history_len: 1
replay_max_size: 50000
replay_min_size: 5000
learning_frequency: 100
update_freq: 100
action_dim: 1
num_units: 250

draw_graph_freq: 10
draw_cv2_freq: 9
draw_movie_freq: 10
